In [5]:
import requests
import pandas as pd
from io import StringIO

url = "https://www.bom.gov.au/climate/mjo/graphics/rmm.74toRealtime.txt"

headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/137.0.0.0 Safari/537.36"
    )
}

response = requests.get(url, headers=headers, timeout=30)
response.raise_for_status()

rmm = pd.read_csv(
    StringIO(response.text),
    sep=r"\s+",
    skiprows=2,
    header=None,
    names=[
        "year", "month", "day",
        "RMM1", "RMM2", "phase", "amplitude",
        "method"
    ],
    na_values=[1e36, "1.E36", 999],
)

rmm["date"] = pd.to_datetime(
    rmm[["year", "month", "day"]].astype(int)
)

rmm = (
    rmm
    .set_index("date")
    .drop(columns=["method"])
    .sort_index()
)

print(rmm.head())
print(rmm.tail())

            year  month  day     RMM1     RMM2  phase  amplitude
date
1974-06-01  1974      6    1  1.63447  1.20304    5.0    2.02948
1974-06-02  1974      6    2  1.60289  1.01512    5.0    1.89729
1974-06-03  1974      6    3  1.51625  1.08551    5.0    1.86476
1974-06-04  1974      6    4  1.50981  1.03573    5.0    1.83092
1974-06-05  1974      6    5  1.55906  1.30518    5.0    2.03326
            year  month  day      RMM1      RMM2  phase  amplitude
date
2024-02-20  2024      2   20 -0.305918  0.305419    8.0   0.432281
2024-02-21  2024      2   21  0.103033  0.071931    5.0   0.125658
2024-02-22  2024      2   22  0.236122  0.248544    6.0   0.342823
2024-02-23  2024      2   23  0.201856  0.325106    6.0   0.382675
2024-02-24  2024      2   24 -0.003146  0.128460    7.0   0.128498

In [7]:
rmm.to_csv("data/input/pacific/MJO.csv")

In [10]:
from pathlib import Path

import numpy as np
import pandas as pd


# ============================================================
# Load ENSO / ONI data
# ============================================================

ENSO_PATH = Path("data/input/pacific/ENSO.csv")

enso_raw = pd.read_csv(ENSO_PATH)

# Handles both cases:
# 1) columns: Date, ONI...
# 2) columns: unnamed index, Date, ONI...
if enso_raw.columns[0].lower().startswith("unnamed"):
    enso_raw = enso_raw.drop(columns=enso_raw.columns[0])

enso_raw = enso_raw.iloc[:, :2].copy()
enso_raw.columns = ["date", "ONI"]

enso_raw["date"] = pd.to_datetime(enso_raw["date"], errors="coerce")
enso_raw["ONI"] = pd.to_numeric(enso_raw["ONI"], errors="coerce")

# NOAA missing values
enso_raw["ONI"] = enso_raw["ONI"].replace([-99.9, -9999.0], np.nan)

enso = (
    enso_raw
    .dropna(subset=["date", "ONI"])
    .set_index("date")
    .sort_index()
)

# ============================================================
# Create useful modelling variables
# ============================================================

enso["ONI_lag1"] = enso["ONI"].shift(1)
enso["ONI_lag3"] = enso["ONI"].shift(3)
enso["ONI_lag6"] = enso["ONI"].shift(6)

enso["ONI_roll3"] = enso["ONI"].rolling(3).mean()
enso["ONI_roll6"] = enso["ONI"].rolling(6).mean()

enso["el_nino"] = (enso["ONI"] >= 0.5).astype(int)
enso["la_nina"] = (enso["ONI"] <= -0.5).astype(int)
enso["neutral"] = ((enso["ONI"] > -0.5) & (enso["ONI"] < 0.5)).astype(int)

print(enso.head())
print(enso.tail())

# Optional: save cleaned version
OUTPUT_PATH = Path("data/processed/pacific/ENSO_clean.csv")
OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

enso.to_csv(OUTPUT_PATH)

print(f"Saved cleaned ENSO data to: {OUTPUT_PATH}")

             ONI  ONI_lag1  ONI_lag3  ONI_lag6  ONI_roll3  ONI_roll6  el_nino  \
date
1950-01-01 -1.53       NaN       NaN       NaN        NaN        NaN        0
1950-02-01 -1.34     -1.53       NaN       NaN        NaN        NaN        0
1950-03-01 -1.16     -1.34       NaN       NaN  -1.343333        NaN        0
1950-04-01 -1.18     -1.16     -1.53       NaN  -1.226667        NaN        0
1950-05-01 -1.07     -1.18     -1.34       NaN  -1.136667        NaN        0

            la_nina  neutral
date
1950-01-01        1        0
1950-02-01        1        0
1950-03-01        1        0
1950-04-01        1        0
1950-05-01        1        0
             ONI  ONI_lag1  ONI_lag3  ONI_lag6  ONI_roll3  ONI_roll6  el_nino  \
date
2025-11-01 -0.55     -0.51     -0.28     -0.02  -0.486667  -0.320000        0
2025-12-01 -0.54     -0.55     -0.40     -0.04  -0.533333  -0.403333        0
2026-01-01 -0.37     -0.54     -0.51     -0.14  -0.486667  -0.441667        0
2026-02-01 -0.15     -0.37     -0.55     -0.28  -0.353333  -0.420000        0
2026-03-01  0.11     -0.15     -0.54     -0.40  -0.136667  -0.335000        0

            la_nina  neutral
date
2025-11-01        1        0
2025-12-01        1        0
2026-01-01        0        1
2026-02-01        0        1
2026-03-01        0        1
Saved cleaned ENSO data to: data\processed\pacific\ENSO_clean.csv

In [9]:
enso

,Date,ONI from CPC missing value -99.9 https://psl.noaa.gov/data/timeseries/month/
0,1950-01-01,-1.53
1,1950-02-01,-1.34
2,1950-03-01,-1.16
3,1950-04-01,-1.18
4,1950-05-01,-1.07
...,...,...
919,2026-08-01,-9999.00
920,2026-09-01,-9999.00
921,2026-10-01,-9999.00
922,2026-11-01,-9999.00
923,2026-12-01,-9999.00

In [12]:
pd.read_csv("data/input/pacific/Nino34.csv")

,Date,NINA34 missing value -99.99 https://psl.noaa.gov/data/timeseries/month/
0,1870-01-01,-1.00
1,1870-02-01,-1.20
2,1870-03-01,-0.83
3,1870-04-01,-0.81
4,1870-05-01,-1.27
...,...,...
1867,2025-08-01,-0.11
1868,2025-09-01,-0.30
1869,2025-10-01,-0.50
1870,2025-11-01,-0.68
1871,2025-12-01,-0.49

In [14]:
from pathlib import Path
import json
import requests
import numpy as np
import pandas as pd


URL = "https://climatereanalyzer.org/clim/sst_daily/json_2clim/oisst2.1_nino3.4_sst_day.json"

RAW_PATH = Path("data/input/pacific/nino34_daily_raw.json")
OUT_PATH = Path("data/processed/pacific/NINO34_daily.csv")

RAW_PATH.parent.mkdir(parents=True, exist_ok=True)
OUT_PATH.parent.mkdir(parents=True, exist_ok=True)


# ============================================================
# Download JSON
# ============================================================

headers = {"User-Agent": "Mozilla/5.0"}

response = requests.get(URL, headers=headers, timeout=30)
response.raise_for_status()

RAW_PATH.write_text(response.text, encoding="utf-8")

data = response.json()


# ============================================================
# Parse yearly daily data
# ============================================================

rows = []

for item in data:
    name = str(item["name"])

    # Keep only actual years: 1981, 1982, ...
    # Skip climatology entries like "1991-2020"
    if not name.isdigit():
        continue

    year = int(name)
    values = item["data"]

    dates = pd.date_range(
        start=f"{year}-01-01",
        periods=len(values),
        freq="D"
    )

    for date, value in zip(dates, values):
        rows.append(
            {
                "date": date,
                "nino34_sst": value,
                "source": item.get("data_source", None),
            }
        )

nino34 = pd.DataFrame(rows)


# ============================================================
# Clean
# ============================================================

nino34["date"] = pd.to_datetime(nino34["date"])
nino34["nino34_sst"] = pd.to_numeric(nino34["nino34_sst"], errors="coerce")

nino34 = (
    nino34
    .dropna(subset=["nino34_sst"])
    .drop_duplicates(subset=["date"])
    .sort_values("date")
    .set_index("date")
)

# Optional: remove source column if you only want numeric model input
nino34 = nino34[["nino34_sst"]]


# ============================================================
# Save
# ============================================================

nino34.to_csv(OUT_PATH)

print(nino34.head())
print(nino34.tail())
print("Date range:", nino34.index.min(), "to", nino34.index.max())
print("Saved to:", OUT_PATH)

            nino34_sst
date
1981-09-01      26.647
1981-09-02      26.633
1981-09-03      26.587
1981-09-04      26.396
1981-09-05      26.339
            nino34_sst
date
2026-05-19      28.835
2026-05-20      28.800
2026-05-21      28.777
2026-05-22      28.740
2026-05-23      28.731
Date range: 1981-09-01 00:00:00 to 2026-05-23 00:00:00
Saved to: data\processed\pacific\NINO34_daily.csv

In [15]:
nino34

            nino34_sst
date
1981-09-01      26.647
1981-09-02      26.633
1981-09-03      26.587
1981-09-04      26.396
1981-09-05      26.339
...                ...
2026-05-19      28.835
2026-05-20      28.800
2026-05-21      28.777
2026-05-22      28.740
2026-05-23      28.731

[16336 rows x 1 columns]

## ERA5

In [2]:
!pip install cdsapi xarray netcdf4 pandas numpy tqdm

Requirement already satisfied: cdsapi in C:\Users\ilang\AppData\Local\Programs\Python\Python313\Lib\site-packages (0.7.7)
Collecting xarray
  Downloading xarray-2026.4.0-py3-none-any.whl.metadata (12 kB)
Collecting netcdf4
  Downloading netcdf4-1.7.4-cp311-abi3-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: pandas in C:\Users\ilang\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.3.1)
Requirement already satisfied: numpy in C:\Users\ilang\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.1.3)
Requirement already satisfied: tqdm in C:\Users\ilang\AppData\Local\Programs\Python\Python313\Lib\site-packages (4.67.1)
Requirement already satisfied: ecmwf-datastores-client>=0.4.0 in C:\Users\ilang\AppData\Local\Programs\Python\Python313\Lib\site-packages (from cdsapi) (0.5.1)
Requirement already satisfied: requests>=2.5.0 in C:\Users\ilang\AppData\Local\Programs\Python\Python313\Lib\site-packages (from cdsapi) (2.32.3)
Requirement already satisfied: packaging>=24.2 in C:\Users\ilang\AppData\Local\Programs\Python\Python313\Lib\site-packages (from xarray) (25.0)
Collecting cftime (from netcdf4)
  Downloading cftime-1.6.5-cp313-cp313-win_amd64.whl.metadata (8.8 kB)
Requirement already satisfied: certifi in C:\Users\ilang\AppData\Local\Programs\Python\Python313\Lib\site-packages (from netcdf4) (2025.4.26)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ilang\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\ilang\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\ilang\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: colorama in C:\Users\ilang\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tqdm) (0.4.6)
Requirement already satisfied: attrs in C:\Users\ilang\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ecmwf-datastores-client>=0.4.0->cdsapi) (25.3.0)
Requirement already satisfied: multiurl>=0.3.7 in C:\Users\ilang\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ecmwf-datastores-client>=0.4.0->cdsapi) (0.3.8)
Requirement already satisfied: typing-extensions in C:\Users\ilang\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ecmwf-datastores-client>=0.4.0->cdsapi) (4.12.2)
Requirement already satisfied: six>=1.5 in C:\Users\ilang\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in C:\Users\ilang\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests>=2.5.0->cdsapi) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\ilang\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests>=2.5.0->cdsapi) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\ilang\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests>=2.5.0->cdsapi) (2.4.0)
Downloading xarray-2026.4.0-py3-none-any.whl (1.4 MB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.4 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.4 MB ? eta -:--:--
   ---------------------- ----------------- 0.8/1.4 MB 932.1 kB/s eta 0:00:01
   ----------------------------- ---------- 1.0/1.4 MB 952.1 kB/s eta 0:00:01
   ---------------------------------------- 1.4/1.4 MB 1.2 MB/s  0:00:02
Downloading netcdf4-1.7.4-cp311-abi3-win_amd64.whl (21.3 MB)
   ---------------------------------------- 0.0/21.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/21.3 MB ? eta -:--:--
   - -------------------------------------- 1.0/21.3 MB 2.6 MB/s eta 0:00:08
   -- ------------------------------------- 1.6/21.3 MB 2.5 MB/s eta 0:00:09
   ---- ----------------------------------- 2.4/21.3 MB 2.9 MB/s eta 0:00:07
   ------ --------------------------------- 3.7/21.3 MB 3.6 MB/s eta 0:00:05
   -------- ------------------------------- 4.7/21.3 MB 3.8 MB/s eta 0:00:05
   ------------ --------------------------- 6.6/21.3 MB 4.6 MB/s eta 0:00:04
   -------------- ------------------------- 7.9/21.3 MB 4.8 MB/s eta 0:00:03
   ------------------ --------------------- 10.0/21.3 MB 5.4 MB/s eta 0:00:03
   --------------------- ------------------ 11.3/21.3 MB 5.5 MB/s eta 0:00:02
   ------------------------- -------------- 13.4/21.3 MB 5.9 MB/s eta 0:00:02
   --------------------------- ------------ 14.7/21.3 MB 5.9 MB/s eta 0:00:02
   ------------------------------- -------- 16.8/21.3 MB 6.2 MB/s eta 0:00:01
   --------------------------------- ------ 18.1/21.3 MB 6.2 MB/s eta 0:00:01
   ------------------------------------- -- 19.9/21.3 MB 6.4 MB/s eta 0:00:01
   ---------------------------------------- 21.3/21.3 MB 6.4 MB/s  0:00:03
Downloading cftime-1.6.5-cp313-cp313-win_amd64.whl (465 kB)
Installing collected packages: cftime, netcdf4, xarray

   ------------- -------------------------- 1/3 [netcdf4]
   ------------- -------------------------- 1/3 [netcdf4]
   ------------- -------------------------- 1/3 [netcdf4]
   -------------------------- ------------- 2/3 [xarray]
   -------------------------- ------------- 2/3 [xarray]
   -------------------------- ------------- 2/3 [xarray]
   -------------------------- ------------- 2/3 [xarray]
   -------------------------- ------------- 2/3 [xarray]
   -------------------------- ------------- 2/3 [xarray]
   -------------------------- ------------- 2/3 [xarray]
   -------------------------- ------------- 2/3 [xarray]
   -------------------------- ------------- 2/3 [xarray]
   -------------------------- ------------- 2/3 [xarray]
   -------------------------- ------------- 2/3 [xarray]
   -------------------------- ------------- 2/3 [xarray]
   -------------------------- ------------- 2/3 [xarray]
   -------------------------- ------------- 2/3 [xarray]
   -------------------------- ------------- 2/3 [xarray]
   -------------------------- ------------- 2/3 [xarray]
   -------------------------- ------------- 2/3 [xarray]
   -------------------------- ------------- 2/3 [xarray]
   -------------------------- ------------- 2/3 [xarray]
   -------------------------- ------------- 2/3 [xarray]
   -------------------------- ------------- 2/3 [xarray]
   -------------------------- ------------- 2/3 [xarray]
   -------------------------- ------------- 2/3 [xarray]
   ---------------------------------------- 3/3 [xarray]

Successfully installed cftime-1.6.5 netcdf4-1.7.4 xarray-2026.4.0

WARNING: Ignoring invalid distribution ~orch (C:\Users\ilang\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~orch (C:\Users\ilang\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~orch (C:\Users\ilang\AppData\Local\Programs\Python\Python313\Lib\site-packages)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
from pathlib import Path

cdsapirc_path = Path.home() / ".cdsapirc"

cds_token = "PASTE_YOUR_TOKEN_HERE"

cdsapirc_text = f"""
url: https://cds.climate.copernicus.eu/api
key: 80b8bbd8-726b-4e75-9e4e-706ba096dc03
""".strip()

cdsapirc_path.write_text(cdsapirc_text)

print(f"Saved CDS API config to: {cdsapirc_path}")

Saved CDS API config to: C:\Users\ilang\.cdsapirc

In [7]:
stations = {
    "BELO_HORIZONTE": {
        "lat": -19.883889,
        "lon": -43.969444,
        "source_note": "INMET Belo Horizonte Pampulha A521"
    },
    "CRUZEIRO_DO_SUL": {
        "lat": -7.610833,
        "lon": -72.681389,
        "source_note": "INMET Cruzeiro do Sul"
    },
    "DARWIN_AIRPORT": {
        "lat": -12.42,
        "lon": 130.89,
        "source_note": "BOM Darwin Airport 014015"
    },
    "GARANHUNS": {
        "lat": -8.910833,
        "lon": -36.493333,
        "source_note": "INMET Garanhuns A322"
    },
    "MANAUS": {
        "lat": -3.103333,
        "lon": -60.016389,
        "source_note": "INMET Manaus A101"
    },
    "SALVADOR": {
        "lat": -13.005833,
        "lon": -38.505833,
        "source_note": "INMET Salvador A401 approximate; verify in INMET catalogue"
    },
    "SAO_PAULO": {
        "lat": -23.496294,
        "lon": -46.620088,
        "source_note": "INMET Sao Paulo Mirante de Santana A701 approximate; verify in INMET catalogue"
    },
    "TORONTO": {
        "lat": 43.68,
        "lon": -79.63,
        "source_note": "Environment Canada Toronto Pearson"
    },
}

In [22]:
import cdsapi
import pandas as pd
import xarray as xr
import numpy as np
from pathlib import Path
from tqdm import tqdm

BASE_DIR = Path("data/input/ERA5")
TEMP_DIR = BASE_DIR / "temperature"
HUMIDITY_DIR = BASE_DIR / "humidity"
RAW_DIR = BASE_DIR / "raw_daily"

TEMP_DIR.mkdir(parents=True, exist_ok=True)
HUMIDITY_DIR.mkdir(parents=True, exist_ok=True)
RAW_DIR.mkdir(parents=True, exist_ok=True)

client = cdsapi.Client()

YEARS = list(range(2006, 2026))

def round_to_era5_grid(x, grid=0.25):
    return round(x / grid) * grid

def era5_single_cell_area(lat, lon):
    """
    ERA5 grid is 0.25 degrees.
    This creates a tiny box exactly around the nearest ERA5 grid point.

    CDS area format: [North, West, South, East]
    """
    grid_lat = round_to_era5_grid(lat, 0.25)
    grid_lon = round_to_era5_grid(lon, 0.25)

    return [
        grid_lat + 0.125,
        grid_lon - 0.125,
        grid_lat - 0.125,
        grid_lon + 0.125,
    ]

def download_station_month(station_name, lat, lon, year, month):
    target = RAW_DIR / f"{station_name}_{year}_{month:02d}_era5_daily.nc"

    if target.exists():
        print(f"Already exists: {target}")
        return target

    request = {
        "product_type": "reanalysis",
        "variable": [
            "2m_temperature",
            "2m_dewpoint_temperature",
        ],
        "year": str(year),
        "month": f"{month:02d}",
        "day": [f"{d:02d}" for d in range(1, 32)],
        "daily_statistic": "daily_mean",
        "time_zone": "UTC+00:00",
        "frequency": "1_hourly",
        "area": era5_single_cell_area(lat, lon),
        "data_format": "netcdf",
        "download_format": "unarchived",
    }

    print(f"Downloading DAILY {station_name} {year}-{month:02d}...")

    client.retrieve(
        "derived-era5-single-levels-daily-statistics",
        request,
        str(target)
    )

    return target

2026-06-13 14:56:38,836 INFO [2026-06-11T00:00:00Z] Upcoming essential maintenance sessions on Data Stores underlying infrastructure on 15 June. Service disruption expected. For further details, please [visit our forum announcement](https://forum.ecmwf.int/t/upcoming-essential-maintenance-sessions-on-data-stores-underlying-infrastructure-part-2/150414).

In [35]:
import zipfile
import tempfile
from pathlib import Path
import pandas as pd
import xarray as xr

SAFE_EXTRACT_BASE = Path(tempfile.gettempdir()) / "era5_extract"
SAFE_EXTRACT_BASE.mkdir(parents=True, exist_ok=True)


def unzip_if_needed(path):
    path = Path(path)

    extract_dir = SAFE_EXTRACT_BASE / path.stem
    extract_dir.mkdir(parents=True, exist_ok=True)

    with open(path, "rb") as f:
        signature = f.read(2)

    if signature == b"PK":
        with zipfile.ZipFile(path, "r") as z:
            z.extractall(extract_dir)
    else:
        raise ValueError(f"Expected ZIP file, but got non-ZIP: {path}")

    return extract_dir


def find_temp_and_dewpoint_files(extract_dir):
    extract_dir = Path(extract_dir)

    nc_files = list(extract_dir.glob("*.nc"))

    print("Files found:")
    for f in nc_files:
        print(f, "exists:", f.exists())

    temp_files = [
        f for f in nc_files
        if "2m_temperature" in f.name and "dewpoint" not in f.name
    ]

    dew_files = [
        f for f in nc_files
        if "2m_dewpoint" in f.name
    ]

    if len(temp_files) != 1:
        raise FileNotFoundError(f"Expected 1 temperature file, found {len(temp_files)}: {temp_files}")

    if len(dew_files) != 1:
        raise FileNotFoundError(f"Expected 1 dewpoint file, found {len(dew_files)}: {dew_files}")

    return temp_files[0], dew_files[0]


def get_time_column(ds):
    for candidate in ["valid_time", "time", "date"]:
        if candidate in ds.coords:
            return candidate
    for candidate in ["valid_time", "time", "date"]:
        if candidate in ds.variables:
            return candidate
    raise ValueError(f"No time coordinate found. Available coords: {list(ds.coords)}")


def dataset_to_daily_df(file_path, lat, lon, variable_name, output_name):
    file_path = str(Path(file_path).resolve())

    ds = xr.open_dataset(file_path, engine="netcdf4")

    time_col = get_time_column(ds)

    target_lon = lon
    if float(ds.longitude.max()) > 180 and lon < 0:
        target_lon = lon % 360

    point = ds.sel(
        latitude=lat,
        longitude=target_lon,
        method="nearest"
    )

    df = point[[variable_name]].to_dataframe().reset_index()
    ds.close()

    df = df[[time_col, variable_name]].rename(
        columns={
            time_col: "date",
            variable_name: output_name
        }
    )

    df["date"] = pd.to_datetime(df["date"])
    df[output_name] = df[output_name] - 273.15

    return df


def extract_nearest_daily(nc_path, station_name, lat, lon):
    extract_dir = unzip_if_needed(nc_path)

    temp_file, dew_file = find_temp_and_dewpoint_files(extract_dir)

    temp_df = dataset_to_daily_df(
        file_path=temp_file,
        lat=lat,
        lon=lon,
        variable_name="t2m",
        output_name="temperature_2m_c"
    )

    dew_df = dataset_to_daily_df(
        file_path=dew_file,
        lat=lat,
        lon=lon,
        variable_name="d2m",
        output_name="dewpoint_2m_c"
    )

    daily = pd.merge(temp_df, dew_df, on="date", how="inner")

    daily["station"] = station_name
    daily["station_lat"] = lat
    daily["station_lon"] = lon

    return daily[[
        "date",
        "station",
        "station_lat",
        "station_lon",
        "temperature_2m_c",
        "dewpoint_2m_c"
    ]]


def save_daily_files(station_name, daily):
    temp = daily[[
        "date",
        "station",
        "station_lat",
        "station_lon",
        "temperature_2m_c"
    ]].copy()

    hum = daily[[
        "date",
        "station",
        "station_lat",
        "station_lon",
        "dewpoint_2m_c"
    ]].copy()

    temp_path = TEMP_DIR / f"{station_name}_ERA5_temperature_2m_daily_2006_2025.csv"
    hum_path = HUMIDITY_DIR / f"{station_name}_ERA5_dewpoint_2m_daily_2006_2025.csv"

    temp.to_csv(temp_path, index=False)
    hum.to_csv(hum_path, index=False)

    print(f"Saved: {temp_path}")
    print(f"Saved: {hum_path}")

In [ ]:
all_daily = []

for station_name, meta in stations.items():
    lat = meta["lat"]
    lon = meta["lon"]

    monthly_daily = []

    for year in YEARS:
        for month in range(1, 13):
            nc_path = download_station_month(
                station_name=station_name,
                lat=lat,
                lon=lon,
                year=year,
                month=month
            )

            daily = extract_nearest_daily(
                nc_path=nc_path,
                station_name=station_name,
                lat=lat,
                lon=lon
            )

            monthly_daily.append(daily)

    station_daily = (
        pd.concat(monthly_daily, ignore_index=True)
          .drop_duplicates(subset=["date", "station"])
          .sort_values("date")
          .reset_index(drop=True)
    )

    save_daily_files(station_name, station_daily)
    all_daily.append(station_daily)

combined = pd.concat(all_daily, ignore_index=True)

combined_path = BASE_DIR / "ERA5_temperature_dewpoint_daily_all_stations_2006_2025.csv"
combined.to_csv(combined_path, index=False)

print(f"Saved combined file: {combined_path}")

combined.head()

Already exists: data\input\ERA5\raw_daily\BELO_HORIZONTE_2006_01_era5_daily.nc
Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2006_01_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2006_01_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2006-02...

2026-06-13 15:06:44,420 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 15:06:44,421 INFO Request ID is c781a038-16d0-46ba-9547-09477d93d807
2026-06-13 15:06:44,831 INFO status has been updated to accepted
2026-06-13 15:07:00,091 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 15:07:00,092 INFO status has been updated to running
2026-06-13 15:08:42,305 INFO status has been updated to successful

b0024c9c20ff3607fcea5eaf8e245f70.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2006_02_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2006_02_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2006-03...

2026-06-13 15:08:48,895 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 15:08:48,896 INFO Request ID is 1523aa63-8740-4304-894a-f35678c503d1
2026-06-13 15:08:49,311 INFO status has been updated to accepted
2026-06-13 15:09:07,449 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 15:09:07,450 INFO status has been updated to running
2026-06-13 15:10:49,797 INFO status has been updated to successful

49a83d36fd066081919dadf476378fe3.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2006_03_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2006_03_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2006-04...

2026-06-13 15:10:56,119 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 15:10:56,120 INFO Request ID is 83b016ba-c2b2-42ca-8710-c5254f1ba1cb
2026-06-13 15:10:56,535 INFO status has been updated to accepted
2026-06-13 15:11:13,022 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 15:11:13,024 INFO status has been updated to running
2026-06-13 15:12:55,400 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 15:13:54,679 INFO status has been updated to successful

d457f2e4b8dfbb090b9d201559692200.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2006_04_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2006_04_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2006-05...

2026-06-13 15:14:01,710 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 15:14:01,711 INFO Request ID is fe99334f-efe7-4061-bc0f-01c563cfe181
2026-06-13 15:14:02,139 INFO status has been updated to accepted
2026-06-13 15:14:25,562 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 15:14:25,563 INFO status has been updated to running
2026-06-13 15:16:59,159 INFO status has been updated to successful

8a8ae00c07c0173ef1cf60d9956e7f15.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2006_05_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2006_05_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2006-06...

2026-06-13 15:17:05,682 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 15:17:05,683 INFO Request ID is c7fa5432-a845-4452-9cb7-b8ab5160bd77
2026-06-13 15:17:06,101 INFO status has been updated to accepted
2026-06-13 15:17:29,345 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 15:17:29,346 INFO status has been updated to running
2026-06-13 15:19:03,586 INFO status has been updated to successful

766834c6170ac3c47710c79ffde59a2b.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2006_06_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2006_06_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2006-07...

2026-06-13 15:19:12,459 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 15:19:12,460 INFO Request ID is c9395993-cd63-4c34-910d-d9257c68fbc9
2026-06-13 15:19:12,882 INFO status has been updated to accepted
2026-06-13 15:20:31,506 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 15:20:31,508 INFO status has been updated to running
2026-06-13 15:22:09,660 INFO status has been updated to successful

8b004e9b0e532265affe00d2175994c2.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2006_07_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2006_07_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2006-08...

2026-06-13 15:22:16,218 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 15:22:16,219 INFO Request ID is faa58635-f376-4833-8bfe-21f14c6bfff5
2026-06-13 15:22:16,637 INFO status has been updated to accepted
2026-06-13 15:22:40,658 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 15:22:40,659 INFO status has been updated to running
2026-06-13 15:25:14,175 INFO status has been updated to successful

dc8037953265f0fc5b2d4904545fbfc2.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2006_08_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2006_08_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2006-09...

2026-06-13 15:25:21,235 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 15:25:21,236 INFO Request ID is 3fa846fc-8f5b-4712-a8d3-bdd740330b19
2026-06-13 15:25:21,652 INFO status has been updated to accepted
2026-06-13 15:25:47,158 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 15:25:47,160 INFO status has been updated to running
2026-06-13 15:28:20,848 INFO status has been updated to successful

9dbce6555939b7c7a12d6a58ad73ef06.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2006_09_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2006_09_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2006-10...

2026-06-13 15:28:27,480 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 15:28:27,482 INFO Request ID is 8ab9533c-00fa-4f8b-9444-e3c675e6333a
2026-06-13 15:28:28,501 INFO status has been updated to accepted
2026-06-13 15:28:38,848 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 15:28:38,849 INFO status has been updated to running
2026-06-13 15:30:26,512 INFO status has been updated to successful

c6f48fddf345b0e0e66ceb60f98ff09f.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2006_10_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2006_10_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2006-11...

2026-06-13 15:30:33,682 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 15:30:33,683 INFO Request ID is a645a519-9283-415a-bf49-7711ebc9d7a4
2026-06-13 15:30:34,087 INFO status has been updated to accepted
2026-06-13 15:31:12,581 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 15:31:12,583 INFO status has been updated to running
2026-06-13 15:33:34,289 INFO status has been updated to successful

6859201c768ce382e65db77bf014b21f.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2006_11_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2006_11_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2006-12...

2026-06-13 15:33:40,839 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 15:33:40,840 INFO Request ID is bda7cc79-c592-47cc-a4b3-1649085320c8
2026-06-13 15:33:41,267 INFO status has been updated to accepted
2026-06-13 15:34:16,376 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 15:34:16,377 INFO status has been updated to running
2026-06-13 15:36:39,130 INFO status has been updated to successful

b14ebe6d5f9032fa7e0253d29ddd495c.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2006_12_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2006_12_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2007-01...

2026-06-13 15:36:45,717 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 15:36:45,718 INFO Request ID is b7ca7cbb-94d6-4bd1-9e98-7ac50a596d5f
2026-06-13 15:36:46,139 INFO status has been updated to accepted
2026-06-13 15:37:01,447 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 15:37:01,450 INFO status has been updated to running
2026-06-13 15:38:43,791 INFO status has been updated to successful

cb171c610e6681cb538501bd5118f31.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2007_01_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2007_01_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2007-02...

2026-06-13 15:38:50,451 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 15:38:50,452 INFO Request ID is 56a668b7-fcc4-41e1-9567-5878b6970562
2026-06-13 15:38:50,866 INFO status has been updated to accepted
2026-06-13 15:39:06,320 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 15:39:06,323 INFO status has been updated to running
2026-06-13 15:40:48,999 INFO status has been updated to successful

714d40e00b7a861db9030d29bdc045e5.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2007_02_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2007_02_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2007-03...

2026-06-13 15:40:56,608 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 15:40:56,608 INFO Request ID is fb8300a7-58bc-4917-9b13-e42b5d76b335
2026-06-13 15:40:57,013 INFO status has been updated to accepted
2026-06-13 15:41:51,269 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 15:41:51,271 INFO status has been updated to running
2026-06-13 15:43:55,437 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 15:45:23,528 INFO status has been updated to successful

3b33e1c7590db944f702b257783e044f.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2007_03_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2007_03_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2007-04...

2026-06-13 15:45:30,025 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 15:45:30,026 INFO Request ID is 0f141d42-c58e-4761-8430-89eb00d3365c
2026-06-13 15:45:30,447 INFO status has been updated to accepted
2026-06-13 15:46:23,271 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 15:46:23,272 INFO status has been updated to running
2026-06-13 15:48:27,539 INFO status has been updated to successful

35177f9b1e38d6d828c3180246cb14a.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2007_04_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2007_04_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2007-05...

2026-06-13 15:48:34,190 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 15:48:34,191 INFO Request ID is add74fa2-9817-4e12-ae4d-ed118d7c9637
2026-06-13 15:48:34,597 INFO status has been updated to accepted
2026-06-13 15:48:49,940 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 15:48:49,941 INFO status has been updated to running
2026-06-13 15:50:32,140 INFO status has been updated to successful

4191fa43822c16186c855bd4de9deacc.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2007_05_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2007_05_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2007-06...

2026-06-13 15:50:38,265 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 15:50:38,266 INFO Request ID is 5cf23f4d-f4bb-4fb2-a358-b2aa4774791f
2026-06-13 15:50:38,858 INFO status has been updated to accepted
2026-06-13 15:51:31,516 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 15:51:31,517 INFO status has been updated to running
2026-06-13 15:53:35,706 INFO status has been updated to successful

e4b302bc7654161f6083e8e4394a98d7.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2007_06_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2007_06_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2007-07...

2026-06-13 15:53:41,953 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 15:53:41,953 INFO Request ID is b2e173e2-cb39-4533-a27a-59af047365cd
2026-06-13 15:53:42,373 INFO status has been updated to accepted
2026-06-13 15:53:52,180 INFO status has been updated to running
2026-06-13 15:53:57,664 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 15:55:39,894 INFO status has been updated to successful

3303740e0698470d19d9d34fda875b50.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2007_07_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2007_07_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2007-08...

2026-06-13 15:55:47,119 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 15:55:47,120 INFO Request ID is 37a9c260-fbf9-48bd-a709-dec4921501b6
2026-06-13 15:55:47,535 INFO status has been updated to accepted
2026-06-13 15:56:10,802 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 15:56:10,803 INFO status has been updated to running
2026-06-13 15:58:44,292 INFO status has been updated to successful

295b91474b47aeb300a26466f8977c87.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2007_08_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2007_08_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2007-09...

2026-06-13 15:58:51,506 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 15:58:51,507 INFO Request ID is 3b22c1d4-9842-4520-91ae-e9c4ce72376e
2026-06-13 15:58:51,925 INFO status has been updated to accepted
2026-06-13 16:00:52,971 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 16:00:52,972 INFO status has been updated to running
2026-06-13 16:01:52,237 INFO status has been updated to successful

60d2ce571f5250dec699084bb89ba446.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2007_09_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2007_09_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2007-10...

2026-06-13 16:01:58,783 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 16:01:58,783 INFO Request ID is 62a18869-2d73-4542-afbb-374ed3711289
2026-06-13 16:01:59,182 INFO status has been updated to accepted
2026-06-13 16:03:17,867 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 16:03:17,867 INFO status has been updated to running
2026-06-13 16:04:56,008 INFO status has been updated to successful

93cd710f7a11ee9da9ba4b8ae6722f4a.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2007_10_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2007_10_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2007-11...

2026-06-13 16:05:02,562 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 16:05:02,563 INFO Request ID is f4bd2944-d4fb-4292-8eca-2844e393d0ef
2026-06-13 16:05:02,981 INFO status has been updated to accepted
2026-06-13 16:06:21,569 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 16:06:21,569 INFO status has been updated to running
2026-06-13 16:07:59,680 INFO status has been updated to successful

13a2a1c852e846713f39b17020cc0ba3.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2007_11_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2007_11_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2007-12...

2026-06-13 16:08:05,921 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 16:08:05,922 INFO Request ID is c1cef434-433a-49f0-8f5e-e16e96ce6ae3
2026-06-13 16:08:06,352 INFO status has been updated to accepted
2026-06-13 16:08:21,608 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 16:08:21,608 INFO status has been updated to running
2026-06-13 16:10:03,884 INFO status has been updated to successful

97c06716adca75b4584cdaae9fb390a5.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2007_12_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2007_12_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2008-01...

2026-06-13 16:10:10,088 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 16:10:10,089 INFO Request ID is c28c8176-6064-4557-b949-c0e68e367415
2026-06-13 16:10:10,505 INFO status has been updated to accepted
2026-06-13 16:10:25,829 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 16:10:25,830 INFO status has been updated to running
2026-06-13 16:13:07,357 INFO status has been updated to successful

3a90a9734036be218c08063102026139.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2008_01_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2008_01_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2008-02...

2026-06-13 16:13:13,840 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 16:13:13,841 INFO Request ID is 2dd5eb1b-a1f3-4d28-9241-2f98c969b63c
2026-06-13 16:13:14,255 INFO status has been updated to accepted
2026-06-13 16:15:12,302 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 16:15:12,302 INFO status has been updated to running
2026-06-13 16:17:39,667 INFO status has been updated to successful

a3a6dac63bdb988a464c5ab4e2622316.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2008_02_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2008_02_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2008-03...

2026-06-13 16:17:46,202 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 16:17:46,203 INFO Request ID is 1656145b-ef12-4f53-87f0-1b782960c7b0
2026-06-13 16:17:46,618 INFO status has been updated to accepted
2026-06-13 16:19:44,113 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 16:19:44,114 INFO status has been updated to running
2026-06-13 16:22:11,512 INFO status has been updated to successful

6049efff35be3f905a8367e5f6289695.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2008_03_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2008_03_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2008-04...

2026-06-13 16:22:17,867 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 16:22:17,868 INFO Request ID is 41a09266-1e4b-4de4-bc43-f08f04859b96
2026-06-13 16:22:18,283 INFO status has been updated to accepted
2026-06-13 16:23:38,153 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 16:23:38,154 INFO status has been updated to running
2026-06-13 16:25:16,296 INFO status has been updated to successful

7cfa5f733788bf0345ea88aef7d69dbf.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2008_04_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2008_04_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2008-05...

2026-06-13 16:25:23,018 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 16:25:23,018 INFO Request ID is 2f39f308-ba07-474f-a0f6-f9f9876858f8
2026-06-13 16:25:23,667 INFO status has been updated to accepted
2026-06-13 16:25:58,907 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 16:25:58,908 INFO status has been updated to running
2026-06-13 16:28:21,838 INFO status has been updated to successful

f6a5a5688f1c419c48d195ababd7b96.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2008_05_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2008_05_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2008-06...

2026-06-13 16:28:28,126 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 16:28:28,126 INFO Request ID is f2ab5de3-7eeb-41c5-9f35-457eb00617b0
2026-06-13 16:28:28,532 INFO status has been updated to accepted
2026-06-13 16:29:05,216 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 16:29:05,217 INFO status has been updated to running
2026-06-13 16:30:27,625 INFO status has been updated to successful

aebed5129cd2170eec7f0b52703c7ecb.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2008_06_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2008_06_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2008-07...

2026-06-13 16:30:33,963 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 16:30:33,964 INFO Request ID is 4b55c850-5da7-4fab-974d-3be2366cfe6c
2026-06-13 16:30:34,393 INFO status has been updated to accepted
2026-06-13 16:41:04,382 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 16:41:04,383 INFO status has been updated to running
2026-06-13 16:43:06,086 INFO status has been updated to successful

3c04e5f8644a237548925eb04415ea23.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2008_07_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2008_07_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2008-08...

2026-06-13 16:43:12,719 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 16:43:12,720 INFO Request ID is 531ad871-1f3d-496d-93cc-77ce8f1c6f3a
2026-06-13 16:43:13,136 INFO status has been updated to accepted
2026-06-13 16:43:48,418 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 16:43:48,419 INFO status has been updated to running
Recovering from connection error [('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))], attempt 1 of 500
Retrying in 120 seconds
2026-06-13 16:47:23,771 INFO status has been updated to successful

220f014358be3ce2c6472d27d8f6a1b1.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2008_08_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2008_08_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2008-09...

2026-06-13 16:47:30,276 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 16:47:30,277 INFO Request ID is 805ba003-2188-4c1d-b221-f0d3b6cd1bbe
2026-06-13 16:47:30,689 INFO status has been updated to accepted
2026-06-13 16:47:43,702 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 16:47:43,703 INFO status has been updated to running
2026-06-13 16:50:31,298 INFO status has been updated to successful

3f14870e01c588becb48dae8ef8f8e5a.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2008_09_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2008_09_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2008-10...

2026-06-13 16:50:37,528 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 16:50:37,529 INFO Request ID is 07c491e0-27bf-45d2-bccd-15fed4d2051c
2026-06-13 16:50:37,943 INFO status has been updated to accepted
2026-06-13 16:50:54,480 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 16:50:54,481 INFO status has been updated to running
2026-06-13 16:53:36,023 INFO status has been updated to successful

d8f1e076d3bafaa814ee544720727efa.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2008_10_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2008_10_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2008-11...

2026-06-13 16:53:42,321 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 16:53:42,322 INFO Request ID is 0bef804d-507f-49a4-b58b-07de6c9b8d5f
2026-06-13 16:53:42,748 INFO status has been updated to accepted
2026-06-13 16:53:52,516 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 16:53:52,517 INFO status has been updated to running
2026-06-13 16:55:40,719 INFO status has been updated to successful

6ab5c0f626b27c669cd7527929497a5f.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2008_11_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2008_11_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2008-12...

2026-06-13 16:55:47,000 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 16:55:47,001 INFO Request ID is a67b607e-79ae-46d8-b90b-7a2d8103fa29
2026-06-13 16:55:47,413 INFO status has been updated to accepted
2026-06-13 16:56:02,655 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 16:56:02,655 INFO status has been updated to running
2026-06-13 16:57:44,882 INFO status has been updated to successful

4fdbffce60667c0d3ceeb90628d60808.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2008_12_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2008_12_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2009-01...

2026-06-13 16:57:51,500 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 16:57:51,501 INFO Request ID is 5f16b0a8-9ff6-4fc4-acab-7b8ef3d11bef
2026-06-13 16:57:51,948 INFO status has been updated to accepted
2026-06-13 16:58:07,858 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 16:58:07,859 INFO status has been updated to running
2026-06-13 17:00:49,402 INFO status has been updated to successful

79bbed03799fef1b325e24513f34c2df.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2009_01_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2009_01_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2009-02...

2026-06-13 17:00:56,737 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 17:00:56,738 INFO Request ID is a48e870a-61a3-4b47-a9be-1969a1b65aa6
2026-06-13 17:00:57,150 INFO status has been updated to accepted
2026-06-13 17:01:21,314 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 17:01:21,315 INFO status has been updated to running
2026-06-13 17:03:54,966 INFO status has been updated to successful

23f3ae512812277bc51026451cbf5015.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2009_02_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2009_02_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2009-03...

2026-06-13 17:04:01,480 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 17:04:01,480 INFO Request ID is 87dc4090-35d3-4530-92f1-51d617b43053
2026-06-13 17:04:01,897 INFO status has been updated to accepted
2026-06-13 17:04:17,349 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 17:04:17,349 INFO status has been updated to running
2026-06-13 17:08:26,910 INFO status has been updated to successful

ebe33be98e87938f5d4e9f7e9cdda2d0.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2009_03_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2009_03_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2009-04...

2026-06-13 17:08:33,257 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 17:08:33,257 INFO Request ID is c7b35ff2-c5b6-481c-86a0-fa620817a020
2026-06-13 17:08:33,667 INFO status has been updated to accepted
2026-06-13 17:08:45,083 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 17:08:45,084 INFO status has been updated to running
2026-06-13 17:11:32,013 INFO status has been updated to successful

d4bfb87037df146736080542a051e7ac.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2009_04_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2009_04_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2009-05...

2026-06-13 17:11:38,348 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 17:11:38,349 INFO Request ID is 097cb672-051d-4bb0-a7fb-8f054bbe4e90
2026-06-13 17:11:38,781 INFO status has been updated to accepted
2026-06-13 17:12:02,023 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 17:12:02,024 INFO status has been updated to running
2026-06-13 17:16:03,763 INFO status has been updated to successful

4928bf677fd44c15dfd2664bd39c12ed.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2009_05_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2009_05_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2009-06...

2026-06-13 17:16:10,019 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 17:16:10,020 INFO Request ID is db987115-da33-4719-82fd-bae4790ee593
2026-06-13 17:16:10,814 INFO status has been updated to accepted
2026-06-13 17:16:22,209 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 17:16:22,210 INFO status has been updated to running
2026-06-13 17:19:10,194 INFO status has been updated to successful

30cbceb5c6be89d6b0827d36baec8ed9.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2009_06_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2009_06_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2009-07...

2026-06-13 17:19:16,358 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 17:19:16,359 INFO Request ID is cdc0fbc5-dafb-40b4-b6f0-ef7e43588573
2026-06-13 17:19:16,758 INFO status has been updated to accepted
2026-06-13 17:19:52,716 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 17:19:52,717 INFO status has been updated to running
2026-06-13 17:22:14,407 INFO status has been updated to successful

4f056ccdd3410c2892a99d695bd03ff0.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2009_07_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2009_07_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2009-08...

2026-06-13 17:22:20,878 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 17:22:20,879 INFO Request ID is 3bc3d10a-0a13-4ae7-8731-fd4f6997c95c
2026-06-13 17:22:21,295 INFO status has been updated to accepted
2026-06-13 17:22:36,583 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 17:22:36,584 INFO status has been updated to running
2026-06-13 17:25:18,231 INFO status has been updated to successful

5e0a25337af9f38155cb2689783dede9.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2009_08_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2009_08_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2009-09...

2026-06-13 17:25:26,535 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 17:25:26,536 INFO Request ID is 2fb55788-9051-4513-9422-d45df4278dfb
2026-06-13 17:25:26,951 INFO status has been updated to accepted
2026-06-13 17:25:50,460 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 17:25:50,461 INFO status has been updated to running
2026-06-13 17:28:24,677 INFO status has been updated to successful

b3622b8a77dd56f10e421f4e15563e5f.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2009_09_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2009_09_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2009-10...

2026-06-13 17:28:33,631 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 17:28:33,632 INFO Request ID is f071d327-8647-47fc-8d2e-a03e1f11aba6
2026-06-13 17:28:34,059 INFO status has been updated to accepted
2026-06-13 17:28:51,453 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 17:28:51,454 INFO status has been updated to running
2026-06-13 17:31:32,949 INFO status has been updated to successful

d308446f3d2aa39f6cc74ec8538f1a6f.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2009_10_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2009_10_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2009-11...

2026-06-13 17:31:39,357 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 17:31:39,358 INFO Request ID is f5810ca9-9d16-4561-8053-e955df800b75
2026-06-13 17:31:40,249 INFO status has been updated to accepted
2026-06-13 17:32:15,497 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 17:32:15,497 INFO status has been updated to running
2026-06-13 17:34:38,475 INFO status has been updated to successful

e550ab029f45a2a6700f7761ef687e61.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2009_11_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2009_11_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2009-12...

2026-06-13 17:34:44,783 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 17:34:44,784 INFO Request ID is 92890c76-3827-4aef-993c-c7b01ac6c5c4
2026-06-13 17:34:45,198 INFO status has been updated to accepted
2026-06-13 17:35:08,849 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 17:35:08,850 INFO status has been updated to running
2026-06-13 17:41:12,080 INFO status has been updated to successful

f07898e63e92ba3e60b6170d1718699e.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2009_12_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2009_12_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2010-01...

2026-06-13 17:41:18,312 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 17:41:18,313 INFO Request ID is ec1bb9c4-06ae-4a67-a2fd-f49f5f7d6776
2026-06-13 17:41:18,740 INFO status has been updated to accepted
2026-06-13 17:41:34,032 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 17:41:34,032 INFO status has been updated to running
2026-06-13 17:43:16,278 INFO status has been updated to successful

c37771d1da12819baafe8f1c63c732d1.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2010_01_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2010_01_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2010-02...

2026-06-13 17:43:22,606 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 17:43:22,607 INFO Request ID is 2db97359-165e-4a38-879a-2a3d605bb047
2026-06-13 17:43:23,028 INFO status has been updated to accepted
2026-06-13 17:43:47,450 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 17:43:47,452 INFO status has been updated to running
2026-06-13 17:45:21,656 INFO status has been updated to successful

cdb5628c3883fd00804f85f57c964255.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2010_02_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2010_02_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2010-03...

2026-06-13 17:45:27,952 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 17:45:27,953 INFO Request ID is 3e3a2219-035a-4329-962e-4cc38f3bc8cc
2026-06-13 17:45:28,574 INFO status has been updated to accepted
2026-06-13 17:45:51,971 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 17:45:51,972 INFO status has been updated to running
2026-06-13 17:48:25,460 INFO status has been updated to successful

49c23e84f76d07dea8f664691ef492e8.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2010_03_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2010_03_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2010-04...

2026-06-13 17:48:32,138 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 17:48:32,139 INFO Request ID is 537cbfe6-f434-4b4c-aab1-f4aaa8a88558
2026-06-13 17:48:32,559 INFO status has been updated to accepted
2026-06-13 17:48:42,918 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 17:48:42,919 INFO status has been updated to running
2026-06-13 17:52:58,778 INFO status has been updated to successful

bdceb27156985c523e4e3ed6c233c441.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2010_04_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2010_04_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2010-05...

2026-06-13 17:53:05,660 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 17:53:05,661 INFO Request ID is eb353bf7-e6e0-4758-a1f4-93429ef75874
2026-06-13 17:53:06,921 INFO status has been updated to accepted
2026-06-13 17:53:19,992 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 17:53:19,992 INFO status has been updated to running
2026-06-13 17:56:07,749 INFO status has been updated to successful

bbea6305437549cddd690bb116ab5d28.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2010_05_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2010_05_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2010-06...

2026-06-13 17:56:13,997 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 17:56:13,998 INFO Request ID is d2fc9aab-0202-493a-8aa6-cfb76aefcefc
2026-06-13 17:56:15,244 INFO status has been updated to accepted
2026-06-13 17:56:30,476 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 17:56:30,477 INFO status has been updated to running
2026-06-13 17:59:14,168 INFO status has been updated to successful

ed9bdaaab2541774a3699bd79e84d665.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2010_06_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2010_06_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2010-07...

2026-06-13 17:59:20,622 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 17:59:20,623 INFO Request ID is 02aa9ec7-e041-45e3-a645-b9b9428d6b37
2026-06-13 17:59:21,034 INFO status has been updated to accepted
2026-06-13 17:59:44,867 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 17:59:44,867 INFO status has been updated to running
2026-06-13 18:02:18,367 INFO status has been updated to successful

2c56d2515ec8aba665ba0647a091745f.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2010_07_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2010_07_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2010-08...

2026-06-13 18:02:24,806 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 18:02:24,807 INFO Request ID is 9e64f42b-45c0-4f85-a70d-97fa3ceeac57
2026-06-13 18:02:25,226 INFO status has been updated to accepted
2026-06-13 18:02:35,293 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 18:02:35,294 INFO status has been updated to running
2026-06-13 18:04:23,019 INFO status has been updated to successful

11e9f3ceaafbb51e2dec474df5094c2e.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2010_08_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2010_08_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2010-09...

2026-06-13 18:04:29,886 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 18:04:29,887 INFO Request ID is e6513980-40e9-4e25-b70f-76390516499c
2026-06-13 18:04:30,295 INFO status has been updated to accepted
2026-06-13 18:04:45,571 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 18:04:45,572 INFO status has been updated to running
2026-06-13 18:07:27,116 INFO status has been updated to successful

a81ac29079d8845717c9adec9bdb0052.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2010_09_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2010_09_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2010-10...

2026-06-13 18:07:34,029 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 18:07:34,030 INFO Request ID is 8592a62e-4255-4276-a73b-3e422d741e70
2026-06-13 18:07:36,161 INFO status has been updated to accepted
2026-06-13 18:07:53,062 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 18:07:53,062 INFO status has been updated to running
2026-06-13 18:09:35,249 INFO status has been updated to successful

4fe4943011e20736859ac5fb927bdabe.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2010_10_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2010_10_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2010-11...

2026-06-13 18:09:41,542 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 18:09:41,543 INFO Request ID is ab262f40-67ea-4220-bf0e-17da774789ed
2026-06-13 18:09:41,994 INFO status has been updated to accepted
2026-06-13 18:12:38,810 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 18:12:38,810 INFO status has been updated to running
2026-06-13 18:14:06,919 INFO status has been updated to successful

eb6b4f9da58212e4dc74ccc494a112c1.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2010_11_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2010_11_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2010-12...

2026-06-13 18:14:13,292 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 18:14:13,293 INFO Request ID is 4b15c98e-a7f5-401f-a114-325fbb5e6ddc
2026-06-13 18:14:13,706 INFO status has been updated to accepted
2026-06-13 18:14:29,040 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 18:14:29,041 INFO status has been updated to running
2026-06-13 18:18:38,614 INFO status has been updated to successful

e874839ed21478a6a3b1deab0620b400.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2010_12_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2010_12_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2011-01...

2026-06-13 18:18:44,852 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 18:18:44,853 INFO Request ID is cec9085c-5ab0-454e-8360-19f65ad22f55
2026-06-13 18:18:45,283 INFO status has been updated to accepted
2026-06-13 18:18:55,795 INFO status has been updated to running
2026-06-13 18:19:09,280 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 18:23:11,818 INFO status has been updated to successful

b4d44fec206dbb3a25fe5b87191aa3ef.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2011_01_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2011_01_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2011-02...

2026-06-13 18:23:18,542 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 18:23:18,543 INFO Request ID is ddc6a973-bd79-4c43-bd52-d4d33c15a66a
2026-06-13 18:23:18,959 INFO status has been updated to accepted
2026-06-13 18:23:36,840 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 18:23:36,841 INFO status has been updated to running
2026-06-13 18:25:19,062 INFO status has been updated to successful

40d704c7cf175fe2f534e6e3e06d7563.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2011_02_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2011_02_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2011-03...

2026-06-13 18:25:25,772 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 18:25:25,773 INFO Request ID is 098d7072-5366-4e61-8de9-77e75a15b05d
2026-06-13 18:25:26,208 INFO status has been updated to accepted
2026-06-13 18:25:41,549 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 18:25:41,549 INFO status has been updated to running
2026-06-13 18:28:23,057 INFO status has been updated to successful

fb0b9f19f6e9154621d3554e91f3c72d.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2011_03_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2011_03_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2011-04...

2026-06-13 18:28:29,619 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 18:28:29,620 INFO Request ID is b3babf48-88e0-4751-b862-568cca394084
2026-06-13 18:28:30,038 INFO status has been updated to accepted
2026-06-13 18:28:39,839 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 18:28:39,839 INFO status has been updated to running
2026-06-13 18:29:48,682 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 18:32:58,095 INFO status has been updated to successful

d15ef45e490f394e3d8641e87ac6fe3e.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2011_04_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2011_04_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2011-05...

2026-06-13 18:33:05,888 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 18:33:05,888 INFO Request ID is a8ccf74d-38da-4a29-9fc9-f9637bb35967
2026-06-13 18:33:06,306 INFO status has been updated to accepted
2026-06-13 18:33:21,585 INFO status has been updated to running
2026-06-13 18:33:29,581 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 18:36:04,658 INFO status has been updated to successful

67b5bff0bbb0fc240ea0e0b0a5dc6b98.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2011_05_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2011_05_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2011-06...

2026-06-13 18:36:11,178 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 18:36:11,179 INFO Request ID is 6a5cdda4-7a0c-4940-9a87-e966805f6016
2026-06-13 18:36:11,599 INFO status has been updated to accepted
2026-06-13 18:36:29,561 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 18:36:29,562 INFO status has been updated to running
2026-06-13 18:39:11,038 INFO status has been updated to successful

58b423eced36965bdbaa8c55f0eea5b0.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2011_06_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2011_06_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2011-07...

2026-06-13 18:39:17,381 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 18:39:17,382 INFO Request ID is 25c13360-b586-4eb6-a112-a1a7730f0569
2026-06-13 18:39:17,800 INFO status has been updated to accepted
2026-06-13 18:39:33,993 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 18:39:33,994 INFO status has been updated to running
2026-06-13 18:41:16,991 INFO status has been updated to successful

176407ce76e714064ddb51e533ac9941.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2011_07_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2011_07_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2011-08...

2026-06-13 18:41:23,301 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 18:41:23,302 INFO Request ID is 8b834f9b-6462-4e8b-aca5-8b0b7a325466
2026-06-13 18:41:23,727 INFO status has been updated to accepted
2026-06-13 18:42:16,438 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 18:42:16,439 INFO status has been updated to running
2026-06-13 18:44:20,607 INFO status has been updated to successful

2648dafd456e8f7a8eb299d7bd2a1fbf.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2011_08_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2011_08_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2011-09...

2026-06-13 18:44:30,316 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 18:44:30,317 INFO Request ID is e11c9901-5a85-4cce-b8a3-cf9ae54b68fc
2026-06-13 18:44:30,734 INFO status has been updated to accepted
2026-06-13 18:44:54,067 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 18:44:54,068 INFO status has been updated to running
2026-06-13 18:47:27,530 INFO status has been updated to successful

f4c0c63163cc615fefae2726078ea261.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2011_09_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2011_09_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2011-10...

2026-06-13 18:47:34,130 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 18:47:34,131 INFO Request ID is faf269c7-7d35-4dc4-b95b-470a957bf266
2026-06-13 18:47:34,565 INFO status has been updated to accepted
2026-06-13 18:47:57,830 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 18:47:57,831 INFO status has been updated to running
2026-06-13 18:50:31,373 INFO status has been updated to successful

65da2aa16bd4092c11f04b61d3119a42.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2011_10_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2011_10_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2011-11...

2026-06-13 18:50:37,786 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 18:50:37,787 INFO Request ID is 2c03581e-6757-4783-8ee5-a2fdd077410a
2026-06-13 18:50:38,187 INFO status has been updated to accepted
2026-06-13 18:50:53,423 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 18:50:53,424 INFO status has been updated to running
2026-06-13 18:53:34,882 INFO status has been updated to successful

3935c14a9124f97ff2f5d16b35055c55.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2011_11_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2011_11_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2011-12...

2026-06-13 18:53:41,162 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 18:53:41,163 INFO Request ID is 0af78035-375b-4dd2-ba6a-e5de267084ab
2026-06-13 18:53:41,589 INFO status has been updated to accepted
2026-06-13 18:54:16,743 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 18:54:16,744 INFO status has been updated to running
2026-06-13 18:55:39,139 INFO status has been updated to successful

8157b7cfaab10c15c9c8ef0b2cc318c6.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2011_12_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2011_12_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2012-01...

2026-06-13 18:55:45,944 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 18:55:45,945 INFO Request ID is 2a8de1b3-8b35-42bd-ab0d-a9c5ed7c79c6
2026-06-13 18:55:46,342 INFO status has been updated to accepted
2026-06-13 18:56:09,628 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 18:56:09,629 INFO status has been updated to running
2026-06-13 18:57:44,008 INFO status has been updated to successful

aeac8e0ec53f13222da95b34ef9a58e6.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2012_01_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2012_01_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2012-02...

2026-06-13 18:57:50,705 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 18:57:50,706 INFO Request ID is 71dd2326-c632-452e-8c85-d632840ef0d0
2026-06-13 18:57:51,132 INFO status has been updated to accepted
2026-06-13 18:58:27,050 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 18:58:27,051 INFO status has been updated to running
2026-06-13 18:59:49,449 INFO status has been updated to successful

2b64ab4f8e3ca206573193671bcd8a43.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2012_02_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2012_02_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2012-03...

2026-06-13 18:59:55,897 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 18:59:55,898 INFO Request ID is b58142da-5f53-454b-96b1-bcb0652a6284
2026-06-13 18:59:56,296 INFO status has been updated to accepted
2026-06-13 19:00:19,653 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 19:00:19,654 INFO status has been updated to running
2026-06-13 19:02:53,116 INFO status has been updated to successful

84f9d92462e3d20951c272c2fff62f7f.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2012_03_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2012_03_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2012-04...

2026-06-13 19:03:02,727 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 19:03:02,728 INFO Request ID is 6c87d046-3e20-4d54-966a-fab598b88a03
2026-06-13 19:03:03,188 INFO status has been updated to accepted
2026-06-13 19:03:13,087 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 19:03:13,088 INFO status has been updated to running
2026-06-13 19:06:01,595 INFO status has been updated to successful

e07bfef3f411d9187507524acf682b72.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2012_04_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2012_04_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2012-05...

2026-06-13 19:06:07,857 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 19:06:07,858 INFO Request ID is 7ed278a1-edfe-4773-8eda-f5396448af95
2026-06-13 19:06:08,276 INFO status has been updated to accepted
2026-06-13 19:07:27,580 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 19:07:27,581 INFO status has been updated to running
2026-06-13 19:12:35,448 INFO status has been updated to successful

3391b82b662bd833006d9e54cdd73026.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2012_05_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2012_05_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2012-06...

2026-06-13 19:12:41,742 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 19:12:41,743 INFO Request ID is ad30df73-40ca-402c-aec5-faa49abf5cf0
2026-06-13 19:12:42,166 INFO status has been updated to accepted
2026-06-13 19:13:17,290 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 19:13:17,291 INFO status has been updated to running
2026-06-13 19:14:39,692 INFO status has been updated to successful

1db225ffff42c3b32860a5d9447d632b.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2012_06_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2012_06_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2012-07...

2026-06-13 19:14:45,874 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 19:14:45,875 INFO Request ID is be22d51f-9e28-498f-a5cc-262ed2128178
2026-06-13 19:14:46,300 INFO status has been updated to accepted
2026-06-13 19:15:01,739 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 19:15:01,739 INFO status has been updated to running
2026-06-13 19:17:43,235 INFO status has been updated to successful

92a6198f258adba3be620f58aadc9b84.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2012_07_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2012_07_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2012-08...

2026-06-13 19:17:49,322 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 19:17:49,322 INFO Request ID is 45e9336d-6da4-47f0-8590-1ab89840c0c9
2026-06-13 19:17:49,736 INFO status has been updated to accepted
2026-06-13 19:18:05,593 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 19:18:05,594 INFO status has been updated to running
2026-06-13 19:20:47,262 INFO status has been updated to successful

e6141193bf07d2d295157fbe8ae7eb0f.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2012_08_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2012_08_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2012-09...

2026-06-13 19:20:53,485 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 19:20:53,486 INFO Request ID is c5c9d9a0-37d0-4595-b44e-03602c59cafa
2026-06-13 19:20:55,591 INFO status has been updated to accepted
2026-06-13 19:21:10,919 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 19:21:10,920 INFO status has been updated to running
2026-06-13 19:23:52,494 INFO status has been updated to successful

accf591d0a805d185d65b2d46dbd62b0.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2012_09_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2012_09_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2012-10...

2026-06-13 19:23:58,823 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 19:23:58,824 INFO Request ID is 0db75c83-4817-4ce2-9672-34b02f5a1b53
2026-06-13 19:23:59,249 INFO status has been updated to accepted
2026-06-13 19:24:15,030 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 19:24:15,031 INFO status has been updated to running
2026-06-13 19:26:56,510 INFO status has been updated to successful

902129ca1bc37a007972cbc47b07e3d9.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2012_10_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2012_10_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2012-11...

2026-06-13 19:27:04,818 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 19:27:04,819 INFO Request ID is 91014597-1ad7-4e2e-9492-692957acd396
2026-06-13 19:27:05,247 INFO status has been updated to accepted
2026-06-13 19:27:58,168 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 19:27:58,169 INFO status has been updated to running
2026-06-13 19:30:06,352 INFO status has been updated to successful

7b66701bd7669255fbc8309212f9f0f1.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2012_11_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2012_11_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2012-12...

2026-06-13 19:30:14,609 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 19:30:14,611 INFO Request ID is 5148734f-ffa8-4c0d-850e-71ea692d3809
2026-06-13 19:30:15,248 INFO status has been updated to accepted
2026-06-13 19:30:28,829 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 19:30:28,831 INFO status has been updated to running
2026-06-13 19:34:45,662 INFO status has been updated to successful

89178b734d17eb14149683d1d049df17.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2012_12_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2012_12_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2013-01...

2026-06-13 19:34:52,501 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 19:34:52,502 INFO Request ID is e4b9009f-be0f-4df8-a04a-c20662d45b4d
2026-06-13 19:34:52,919 INFO status has been updated to accepted
2026-06-13 19:35:18,609 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 19:35:18,610 INFO status has been updated to running
2026-06-13 19:36:52,946 INFO status has been updated to successful

baf5751ddeefbcf54c1df2d26bf14f76.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2013_01_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2013_01_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2013-02...

2026-06-13 19:36:59,565 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 19:36:59,567 INFO Request ID is f241d571-be90-4d82-af95-1420d3f3f281
2026-06-13 19:36:59,985 INFO status has been updated to accepted
2026-06-13 19:37:23,718 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 19:37:23,719 INFO status has been updated to running
2026-06-13 19:39:57,958 INFO status has been updated to successful

3196c700243f47f79ae2c1b06296438a.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2013_02_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2013_02_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2013-03...

2026-06-13 19:40:04,523 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 19:40:04,524 INFO Request ID is d79c100a-1bb2-4d47-9911-4ee985fb4b01
2026-06-13 19:40:04,943 INFO status has been updated to accepted
2026-06-13 19:40:57,519 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 19:40:57,520 INFO status has been updated to running
2026-06-13 19:43:01,753 INFO status has been updated to successful

c8d2f5a9101c61dc59e65fdac3884d3b.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2013_03_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2013_03_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2013-04...

2026-06-13 19:43:08,195 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 19:43:08,196 INFO Request ID is f8cf9408-b43f-4f4e-b3ed-44c25ae6066d
2026-06-13 19:43:08,620 INFO status has been updated to accepted
2026-06-13 19:43:18,388 INFO status has been updated to running
2026-06-13 19:43:23,856 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 19:46:05,377 INFO status has been updated to successful

e37579e43ebf7dfccc556f497137b809.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2013_04_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2013_04_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2013-05...

2026-06-13 19:46:12,736 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 19:46:12,736 INFO Request ID is 6744efd9-3a58-4070-ab37-f6e3749e60b0
2026-06-13 19:46:13,153 INFO status has been updated to accepted
2026-06-13 19:46:36,496 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 19:46:36,497 INFO status has been updated to running
2026-06-13 19:49:11,137 INFO status has been updated to successful

ba3ff6c3c50037775a1648c8a406d9af.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2013_05_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2013_05_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2013-06...

2026-06-13 19:49:17,670 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 19:49:17,671 INFO Request ID is c17500b6-858b-4fdd-897b-3a9980b047af
2026-06-13 19:49:18,092 INFO status has been updated to accepted
2026-06-13 19:49:55,250 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 19:49:55,251 INFO status has been updated to running
2026-06-13 19:52:16,933 INFO status has been updated to successful

329fdb35d7509456bc30af6c21c497d5.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2013_06_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2013_06_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2013-07...

2026-06-13 19:52:23,522 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 19:52:23,523 INFO Request ID is 4b14111b-a791-43b3-ba42-f2e08a119d9e
2026-06-13 19:52:23,931 INFO status has been updated to accepted
2026-06-13 19:55:21,097 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 19:55:21,097 INFO status has been updated to running
2026-06-13 19:56:49,211 INFO status has been updated to successful

39387d9ee11925e6e329182e7067197b.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2013_07_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2013_07_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2013-08...

2026-06-13 19:56:56,331 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 19:56:56,332 INFO Request ID is 93395b74-0063-47bd-aa08-1c5b2d46fa67
2026-06-13 19:56:56,760 INFO status has been updated to accepted
2026-06-13 20:01:22,336 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 20:01:22,337 INFO status has been updated to running
2026-06-13 20:03:23,945 INFO status has been updated to successful

e5d76ed345f38fdf15cc41063e3c9b94.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2013_08_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2013_08_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2013-09...

2026-06-13 20:03:30,339 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 20:03:30,340 INFO Request ID is 4f11ca7d-406c-4ad5-a736-80385285db14
2026-06-13 20:03:30,753 INFO status has been updated to accepted
2026-06-13 20:11:59,516 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 20:11:59,517 INFO status has been updated to running
2026-06-13 20:14:01,103 INFO status has been updated to successful

5f2c113992174395ed4c9e0fefb5fa6d.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2013_09_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2013_09_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2013-10...

2026-06-13 20:14:07,364 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 20:14:07,365 INFO Request ID is 81339af3-7e9b-433a-b094-2adc53a37efe
2026-06-13 20:14:07,780 INFO status has been updated to accepted
2026-06-13 20:22:35,882 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 20:22:35,883 INFO status has been updated to running
2026-06-13 20:24:37,494 INFO status has been updated to successful

93a266c9767dfc2341d7842515870c9.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2013_10_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2013_10_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2013-11...

2026-06-13 20:24:43,804 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 20:24:43,805 INFO Request ID is 3500c3a9-617d-45fd-b702-9e075aae4526
2026-06-13 20:24:44,227 INFO status has been updated to accepted
2026-06-13 20:35:14,233 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 20:35:14,234 INFO status has been updated to running
2026-06-13 20:37:15,848 INFO status has been updated to successful

f87960c724fd40ba93a65dadad32f668.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2013_11_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2013_11_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2013-12...

2026-06-13 20:37:22,046 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 20:37:22,047 INFO Request ID is dd0eb81f-ab1f-429f-a145-a71526f8ad80
2026-06-13 20:37:22,539 INFO status has been updated to accepted
2026-06-13 20:51:58,666 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 20:51:58,668 INFO status has been updated to running
2026-06-13 20:54:00,287 INFO status has been updated to successful

ec42c0f4f17c2391d2bb0550315a3c17.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2013_12_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2013_12_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2014-01...

2026-06-13 20:54:07,090 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 20:54:07,091 INFO Request ID is 92a5f6d4-8b90-4e59-b629-e2ede8afe891
2026-06-13 20:54:07,511 INFO status has been updated to accepted
2026-06-13 21:06:40,298 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 21:06:40,299 INFO status has been updated to running
2026-06-13 21:08:41,940 INFO status has been updated to successful

1e81a4965c071d553a348c20a5824cdd.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2014_01_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2014_01_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2014-02...

2026-06-13 21:08:48,460 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 21:08:48,462 INFO Request ID is 30a82d97-0e5c-4ceb-8f3e-fb2bdac469fd
2026-06-13 21:08:48,864 INFO status has been updated to accepted
2026-06-13 21:21:20,303 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 21:21:20,304 INFO status has been updated to running
2026-06-13 21:23:21,895 INFO status has been updated to successful

cb5eb86fb8219cab1bd3c905da85109a.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2014_02_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2014_02_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2014-03...

2026-06-13 21:23:30,931 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 21:23:30,932 INFO Request ID is 8bee28ac-4cfd-42db-afe5-b18a46c3dfc7
2026-06-13 21:23:32,096 INFO status has been updated to accepted
2026-06-13 21:38:08,210 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 21:38:08,211 INFO status has been updated to running
2026-06-13 21:40:09,816 INFO status has been updated to successful

6a0a306ca8dcdab98b4411e1af772798.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2014_03_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2014_03_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2014-04...

2026-06-13 21:40:16,389 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 21:40:16,390 INFO Request ID is 9d194bc1-21bd-40a4-8ad7-a2f7f7bece4d
2026-06-13 21:40:16,810 INFO status has been updated to accepted
2026-06-13 21:52:48,361 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 21:52:48,362 INFO status has been updated to running
2026-06-13 21:56:54,030 INFO status has been updated to successful

f61eb9893ae6e058743a0d8cd3d35f0c.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2014_04_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2014_04_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2014-05...

2026-06-13 21:57:00,592 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 21:57:00,594 INFO Request ID is 1cd3f2b1-48b0-405e-afb6-cac5adf5e9c0
2026-06-13 21:57:00,996 INFO status has been updated to accepted
2026-06-13 22:09:32,514 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 22:09:32,515 INFO status has been updated to running
2026-06-13 22:11:34,184 INFO status has been updated to successful

6d9bea1fce260e63f175ebddc7c05fb6.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2014_05_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2014_05_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2014-06...

2026-06-13 22:11:40,759 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 22:11:40,760 INFO Request ID is 3bf6b387-e9ad-4871-8174-df02aa355b87
2026-06-13 22:11:41,196 INFO status has been updated to accepted
2026-06-13 22:24:13,812 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 22:24:13,814 INFO status has been updated to running
2026-06-13 22:26:15,731 INFO status has been updated to successful

a0f6869c3e086b0b773dc1ad3b1d8a06.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2014_06_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2014_06_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2014-07...

2026-06-13 22:26:22,453 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 22:26:22,455 INFO Request ID is d4e77eb5-37ad-4850-aa44-5217118c13ac
2026-06-13 22:26:22,876 INFO status has been updated to accepted
2026-06-13 22:42:59,356 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 22:42:59,357 INFO status has been updated to running
2026-06-13 22:47:02,632 INFO status has been updated to successful

f3204eb02f41cab7b08c6867c2b1532e.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2014_07_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2014_07_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2014-08...

2026-06-13 22:47:09,972 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 22:47:09,973 INFO Request ID is d995222a-b977-4413-8ca2-588b82f9aa3d
2026-06-13 22:47:10,389 INFO status has been updated to accepted
2026-06-13 23:03:47,489 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 23:03:47,490 INFO status has been updated to running
2026-06-13 23:07:51,852 INFO status has been updated to successful

4d170e9397f49115111decaedfb76918.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2014_08_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2014_08_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2014-09...

2026-06-13 23:07:58,164 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 23:07:58,165 INFO Request ID is e1dc76ee-4961-4b0e-b5bd-f47429690286
2026-06-13 23:07:58,578 INFO status has been updated to accepted
2026-06-13 23:26:35,559 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 23:26:35,560 INFO status has been updated to running
2026-06-13 23:28:37,160 INFO status has been updated to successful

f9afcdfd82f6473a971a52a1ccb5d6f1.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2014_09_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2014_09_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2014-10...

2026-06-13 23:28:43,971 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 23:28:43,972 INFO Request ID is 61c51765-cd46-4db8-8b0a-f81a09a29f45
2026-06-13 23:28:45,546 INFO status has been updated to accepted
2026-06-13 23:43:22,974 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 23:43:22,975 INFO status has been updated to successful

c0a747da3b294d669b9e52fa3ff9cd45.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2014_10_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2014_10_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2014-11...

2026-06-13 23:43:29,301 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-13 23:43:29,302 INFO Request ID is 665f8a97-e2ab-45c0-82fa-834bde78c147
2026-06-13 23:43:29,737 INFO status has been updated to accepted
2026-06-13 23:58:02,158 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-13 23:58:02,159 INFO status has been updated to running
2026-06-14 00:00:03,760 INFO status has been updated to successful

da4887b49d1f290d53df73f86671f803.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2014_11_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2014_11_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2014-12...

2026-06-14 00:00:11,220 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-14 00:00:11,221 INFO Request ID is ed10c213-b4a8-4c41-a528-b7ac8fdc9e24
2026-06-14 00:00:11,642 INFO status has been updated to accepted
2026-06-14 00:12:43,146 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-14 00:12:43,147 INFO status has been updated to running
2026-06-14 00:14:44,785 INFO status has been updated to successful

3ae05e2cef02f128f972d42bf6a6f53e.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2014_12_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2014_12_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2015-01...

2026-06-14 00:14:51,380 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-14 00:14:51,381 INFO Request ID is 9f1b0102-d148-42cb-9a1e-746c6db7928f
2026-06-14 00:14:51,786 INFO status has been updated to accepted
2026-06-14 00:33:28,082 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-14 00:33:28,083 INFO status has been updated to running
2026-06-14 00:35:29,702 INFO status has been updated to successful

517f4ed5c851ff6b0072b555b097104a.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2015_01_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2015_01_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2015-02...

2026-06-14 00:35:37,034 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-14 00:35:37,035 INFO Request ID is 19ae9781-63b1-4746-841c-9ee1b413ae0a
2026-06-14 00:35:37,458 INFO status has been updated to accepted
2026-06-14 00:50:10,603 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-14 00:50:10,603 INFO status has been updated to running
2026-06-14 00:52:12,191 INFO status has been updated to successful

af8bae15e09fb02af175aa4efda009a0.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2015_02_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2015_02_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2015-03...

2026-06-14 00:52:18,482 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-14 00:52:18,483 INFO Request ID is 60b2702a-5b3d-4274-8d87-c9b89b4800cf
2026-06-14 00:52:18,906 INFO status has been updated to accepted
2026-06-14 01:12:56,747 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-14 01:12:56,747 INFO status has been updated to running
2026-06-14 01:16:59,947 INFO status has been updated to successful

b8f4a94ee7b5f685a980dcfa4212a646.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2015_03_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2015_03_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2015-04...

2026-06-14 01:17:06,203 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-14 01:17:06,204 INFO Request ID is ffd5daf7-b187-489d-ae7b-5613b0fd8521
2026-06-14 01:17:06,615 INFO status has been updated to accepted
2026-06-14 01:41:50,378 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-14 01:41:50,378 INFO status has been updated to running
2026-06-14 01:43:51,987 INFO status has been updated to successful

6658ebae0ddc2594f37614f00efde87b.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2015_04_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2015_04_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2015-05...

2026-06-14 01:43:58,598 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-14 01:43:58,599 INFO Request ID is a9769298-a593-4b38-92d3-76dd6d6819f2
2026-06-14 01:43:59,023 INFO status has been updated to accepted
2026-06-14 02:08:42,536 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-14 02:08:42,537 INFO status has been updated to running
2026-06-14 02:12:45,770 INFO status has been updated to successful

dd3dd83af701057119de64cd7950bbdd.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2015_05_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2015_05_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2015-06...

2026-06-14 02:12:53,172 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-14 02:12:53,173 INFO Request ID is fe11b05d-3957-4d3d-a449-8404e3ee74c7
2026-06-14 02:12:55,330 INFO status has been updated to accepted
2026-06-14 02:43:41,298 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-14 02:43:41,298 INFO status has been updated to running
2026-06-14 02:45:42,907 INFO status has been updated to successful

67f66395fffa93be456264ab71a3550a.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2015_06_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2015_06_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2015-07...

2026-06-14 02:45:50,585 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-14 02:45:50,586 INFO Request ID is 6107ed7e-2b9e-4fc2-bf54-11becdc66d29
2026-06-14 02:45:51,364 INFO status has been updated to accepted
2026-06-14 03:18:40,814 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-14 03:18:40,816 INFO status has been updated to running
2026-06-14 03:20:42,436 INFO status has been updated to successful

7e613bec108a898fc2300eba0f5d6e37.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2015_07_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2015_07_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2015-08...

2026-06-14 03:20:48,737 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-14 03:20:48,737 INFO Request ID is 0020da66-584b-475e-aadd-2e1bbe877f8d
2026-06-14 03:20:49,150 INFO status has been updated to accepted
2026-06-14 03:57:46,670 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-14 03:57:46,671 INFO status has been updated to running
2026-06-14 03:59:48,317 INFO status has been updated to successful

c194beee8e3ac91da0b96bf1d553360f.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2015_08_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2015_08_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2015-09...

2026-06-14 03:59:54,766 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-14 03:59:54,767 INFO Request ID is 67cd58cb-bb1f-4610-a838-16910318827f
2026-06-14 03:59:55,184 INFO status has been updated to accepted
Recovering from HTTP error [500 Internal Server Error], attempt 1 of 500
Retrying in 120 seconds
2026-06-14 04:35:31,781 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-14 04:35:31,781 INFO status has been updated to successful

293f326de87ac6bf6e56fc6a6afd9710.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2015_09_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2015_09_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2015-10...

2026-06-14 04:35:37,998 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-14 04:35:37,999 INFO Request ID is ff9cfa23-784c-4b0c-8c65-3af1c65ad646
2026-06-14 04:35:38,418 INFO status has been updated to accepted
2026-06-14 05:12:30,457 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-14 05:12:30,458 INFO status has been updated to successful

fb1d7df19166b8b6d1336bcf8ca067bd.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2015_10_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2015_10_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2015-11...

2026-06-14 05:12:38,064 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-14 05:12:38,065 INFO Request ID is e4001d36-c072-4fac-b9f5-c5fa4a9e5ebf
2026-06-14 05:12:38,479 INFO status has been updated to accepted
2026-06-14 05:55:38,447 WARNING Download format not supported for this dataset. Defaulting to as_source.
2026-06-14 05:55:38,448 INFO status has been updated to running
2026-06-14 05:57:40,887 INFO status has been updated to successful

ba1237a8f77d8c33965db4a12581617e.zip:   0%|          | 0.00/49.5k [00:00<?, ?B/s]

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2015_11_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2015_11_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True
Downloading DAILY BELO_HORIZONTE 2015-12...

2026-06-14 05:57:47,181 WARNING [2026-06-08T00:00:00] An issue with the following parameters has been identified:

- `maximum_2m_temperature_since_previous_post_processing`
- `minimum_2m_temperature_since_previous_post_processing`
- `10m_wind_gust_since_previous_post_processing`
- `maximum_total_precipitation_rate_since_previous_post_processing`
- `minimum_total_precipitation_rate_since_previous_post_processing`

Please refer to the documented [Known issue](https://confluence.ecmwf.int/display/CKB/ERA5+family+post-processed+daily+statistics+documentation#ERA5familypostprocesseddailystatisticsdocumentation-KnownIssues) for details. **Data downloaded for the parameters listed above should not be used.** A fix is to be released as soon as possible. Please [follow updates on this topic on our Forum announcement](https://forum.ecmwf.int/t/issue-affecting-some-parameters-from-the-era5-post-processed-daily-statistics-on-single-levels/15057).
2026-06-14 05:57:47,182 INFO Request ID is e1532e70-3eb1-497a-9ddf-f5044c26a1e7
2026-06-14 05:57:47,631 INFO status has been updated to accepted

In [36]:
daily = extract_nearest_daily(
    "data/input/ERA5/raw_daily/BELO_HORIZONTE_2006_01_era5_daily.nc",
    "BELO_HORIZONTE",
    -19.883889,
    -43.969444
)

daily.head()

Files found:
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2006_01_era5_daily\2m_dewpoint_temperature_0_daily-mean.nc exists: True
C:\Users\ilang\AppData\Local\Temp\era5_extract\BELO_HORIZONTE_2006_01_era5_daily\2m_temperature_stream-oper_daily-mean.nc exists: True

,date,station,station_lat,station_lon,temperature_2m_c,dewpoint_2m_c
0,2006-01-01,BELO_HORIZONTE,-19.883889,-43.969444,22.339172,17.851685
1,2006-01-02,BELO_HORIZONTE,-19.883889,-43.969444,21.696472,17.959106
2,2006-01-03,BELO_HORIZONTE,-19.883889,-43.969444,21.860992,18.134094
3,2006-01-04,BELO_HORIZONTE,-19.883889,-43.969444,22.407471,17.738892
4,2006-01-05,BELO_HORIZONTE,-19.883889,-43.969444,21.219299,17.531799

In [26]:
test_file = files[0]

with open(test_file, "rb") as f:
    print(f.read(20))

b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x03&\xcd\\\xa8t\xccnfb'

## Yearly ERA5

In [2]:
from pathlib import Path
import cdsapi
import pandas as pd

BASE_DIR = Path("data/input/ERA5")
TEMP_DIR = BASE_DIR / "temperature"
HUMIDITY_DIR = BASE_DIR / "humidity"
RAW_DIR = BASE_DIR / "raw_timeseries"

TEMP_DIR.mkdir(parents=True, exist_ok=True)
HUMIDITY_DIR.mkdir(parents=True, exist_ok=True)
RAW_DIR.mkdir(parents=True, exist_ok=True)

client = cdsapi.Client()

START_DATE = "2015-12-01"
END_DATE = "2025-12-31"

def download_station_timeseries(station_name, lat, lon):
    target = RAW_DIR / f"{station_name}_ERA5_timeseries_2015_12_2025_12.csv"

    if target.exists():
        print(f"Already exists: {target}")
        return target

    request = {
        "variable": [
            "2m_temperature",
            "2m_dewpoint_temperature",
        ],
        "location": {
            "latitude": lat,
            "longitude": lon,
        },
        "date": [f"{START_DATE}/{END_DATE}"],
        "data_format": "csv",
    }

    print(f"Downloading ERA5 time-series for {station_name}...")

    client.retrieve(
        "reanalysis-era5-single-levels-timeseries",
        request,
        str(target)
    )

    return target

2026-06-14 06:36:32,756 INFO [2026-06-11T00:00:00Z] Upcoming essential maintenance sessions on Data Stores underlying infrastructure on 15 June. Service disruption expected. For further details, please [visit our forum announcement](https://forum.ecmwf.int/t/upcoming-essential-maintenance-sessions-on-data-stores-underlying-infrastructure-part-2/150414).

In [3]:
def process_timeseries_csv(csv_path, station_name, lat, lon):
    df = pd.read_csv(csv_path)

    print("Columns:", df.columns.tolist())
    print(df.head())

    # Try to detect time column
    possible_time_cols = ["time", "valid_time", "date", "datetime"]
    time_col = None

    for col in possible_time_cols:
        if col in df.columns:
            time_col = col
            break

    if time_col is None:
        raise ValueError(f"Could not find time column. Columns are: {df.columns.tolist()}")

    df[time_col] = pd.to_datetime(df[time_col])
    df["date"] = df[time_col].dt.date

    # Try to detect variable columns
    temp_col = None
    dew_col = None

    for col in df.columns:
        low = col.lower()
        if "2m_temperature" in low or low == "t2m":
            temp_col = col
        if "2m_dewpoint" in low or low == "d2m":
            dew_col = col

    if temp_col is None:
        raise ValueError(f"Could not find temperature column. Columns are: {df.columns.tolist()}")

    if dew_col is None:
        raise ValueError(f"Could not find dewpoint column. Columns are: {df.columns.tolist()}")

    daily = (
        df.groupby("date", as_index=False)
          .agg(
              temperature_2m_c=(temp_col, "mean"),
              dewpoint_2m_c=(dew_col, "mean"),
          )
    )

    # ERA5 likely comes in Kelvin
    if daily["temperature_2m_c"].mean() > 100:
        daily["temperature_2m_c"] = daily["temperature_2m_c"] - 273.15

    if daily["dewpoint_2m_c"].mean() > 100:
        daily["dewpoint_2m_c"] = daily["dewpoint_2m_c"] - 273.15

    daily["date"] = pd.to_datetime(daily["date"])
    daily["station"] = station_name
    daily["station_lat"] = lat
    daily["station_lon"] = lon

    return daily[[
        "date",
        "station",
        "station_lat",
        "station_lon",
        "temperature_2m_c",
        "dewpoint_2m_c",
    ]]


def save_station_files(station_name, daily):
    temp_path = TEMP_DIR / f"{station_name}_ERA5_temperature_2m_daily_2015_12_2025_12.csv"
    hum_path = HUMIDITY_DIR / f"{station_name}_ERA5_dewpoint_2m_daily_2015_12_2025_12.csv"

    daily[[
        "date", "station", "station_lat", "station_lon", "temperature_2m_c"
    ]].to_csv(temp_path, index=False)

    daily[[
        "date", "station", "station_lat", "station_lon", "dewpoint_2m_c"
    ]].to_csv(hum_path, index=False)

    print(f"Saved: {temp_path}")
    print(f"Saved: {hum_path}")

In [8]:
stations_to_run = {
    "BELO_HORIZONTE": stations["BELO_HORIZONTE"]
}

all_daily = []

for station_name, meta in stations_to_run.items():
    lat = meta["lat"]
    lon = meta["lon"]

    csv_path = download_station_timeseries(station_name, lat, lon)

    daily = process_timeseries_csv(csv_path, station_name, lat, lon)

    save_station_files(station_name, daily)
    all_daily.append(daily)

combined = pd.concat(all_daily, ignore_index=True)

combined_path = BASE_DIR / "ERA5_temperature_dewpoint_daily_BELO_HORIZONTE_2015_12_2025_12.csv"
combined.to_csv(combined_path, index=False)

combined.head()

Downloading ERA5 time-series for BELO_HORIZONTE...

2026-06-14 06:37:27,949 INFO [2026-02-16T00:00:00] - To generate this ERA5 hourly time series dataset, **homogenisation conventions have been applied to the ERA5 source GRIB data** to ensure consistency, usability, and alignment across chosen variables and time steps. The processed data were then written to an **ARCO Zarr archive**, enabling efficient cloud-optimised access and scalable data retrieval. Please refer to the [user guide](https://confluence.ecmwf.int/x/R6cfHg) for details.

- The dataset presented here is a subset of selected parameters from the full [CDS ERA5 hourly data on single levels (1940–present)](https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels?tab=overview). **Requirements for additional parameters may be considered**. Please raise your request with ECMWF Support [here](https://jira.ecmwf.int/plugins/servlet/desk/portal/1/create/202).
2026-06-14 06:37:27,950 INFO Request ID is 88d3f870-4859-4c3f-9727-67274fb11217
2026-06-14 06:37:28,361 INFO status has been updated to accepted
2026-06-14 06:37:43,653 INFO status has been updated to running
2026-06-14 06:37:51,663 INFO status has been updated to successful

8268ee4ae12b3cc6fbacd7a7c317604b.zip:   0%|          | 0.00/968k [00:00<?, ?B/s]

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf5 in position 10: invalid start byte